### ISSUE TITLE
Apparent typo "qua human" in Labor.md

### ISSUE THREAD

**Issue by erlend-sh** [WorldAfterCapital/WorldAfterCapital#38]
`Labor.md` has the following sentence:

> We may find that the best candidate is a cultural shift that leads us to value goods and services produced by humans qua human production.

Unless I'm misunderstanding what "qua human" is supposed to mean, it appears to be a typo.

**Comment by albertwenger** [comment]
Not a typo but I have removed it there and clarified it later. It comes from Latin and means "by virtue of", see https://www.collinsdictionary.com/dictionary/english/qua
