### ISSUE TITLE
Remove redundant description of ISPs

### ISSUE THREAD

**Issue by erlend-sh** [WorldAfterCapital/WorldAfterCapital#39]
In `Informational.md` under the "No Artificial Fast and Slow Lanes" heading it says:

> The same additional equipment used by governments to re-impose geographic boundaries on the Internet is also used by ISPs (Internet Service Providers, i.e. companies that provide access to the Internet)

However a few paragraphs prior, at the end of "Access to the Internet", you've already provided this exact same explainer.

**Comment by albertwenger** [comment]
Fixed
