### ISSUE TITLE
Source for India rejecting Facebook's internet plan

### ISSUE THREAD

**Issue by erlend-sh** [WorldAfterCapital/WorldAfterCapital#40]
`Informational.md` ends with a mention of India's rejection of Facebook's "free" internet offering. There are many good options for reference material here.

My suggestion:
https://www.theguardian.com/technology/2016/may/12/facebook-free-basics-india-zuckerberg

**Comment by albertwenger** [comment]
Great suggestion. Implemented. PS Sorry for not getting to these when you first opened the.

**Comment by erlend-sh** [comment]
No worries! Feel free to ping me once there’s a major new version in need of review :)
